# Generated by Django 5.2.7 on 2025-10-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='legth',
            new_name='duration_seconds',
        ),
    ]
