# Generated by Django 5.2.7 on 2025-10-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_rename_legth_workout_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
